Repository bolti95/jidiFrontend, pull requests merged in 2020-11, with the labels that each got.

#9 add component folder
  components/Homepage.js
Labels: enhancement

#10 moved comps folder
  src/components/Homepage.js
Labels: help wanted

#11 added Home component
  src/App.js
  src/components/Home.css
  src/components/Home.js
  src/components/Homepage.js
Labels: good first issue

#17 Basket n two
  package-lock.json
  package.json
  src/App.js
  src/components/Basket.js
  src/components/Checkout.js
  src/components/Homepage.js
  src/components/Nav.js
Labels: help wanted

#22 nav bar complete, store.js, actions folder, reducers
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/actions/addAction.js
  src/actions/types.js
  src/components/Basket.js
  src/components/Home.js
  src/components/Nav.js
  src/reducers/basketReducer.js
  src/reducers/index.js
  src/store.js
Labels: help wanted

#24 Newproducts
  src/components/Home.css
  src/components/Home.js
  src/components/images/desktop.jpg
  src/components/images/fitbit.jpg
  src/components/images/iphone.jpg
  src/components/images/laptop.jpg
  src/components/images/phonecase.jpg
Labels: enhancement

#30 added form to checkout
  src/.store 2.js.icloud
  src/App.js
  src/actions/.addAction 2.js.icloud
  src/actions/.types 2.js.icloud
  src/components/Basket.js
  src/components/Checkout.css
  src/components/Checkout.js
  src/reducers/.basketReducer 2.js.icloud
  src/reducers/.index 2.js.icloud
Labels: enhancement

#35 this is new code
  src/components/Basket.js
  src/components/Checkout.js
  src/reducers/basketReducer.js
Labels: help wanted

#36 added from on checkout page
  src/components/Checkout.js
Labels: help wanted

#38 this is the new code. Form is different and needs the thank you message
  src/actions/createCustomerOrder.js
  src/actions/types.js
  src/components/Checkout.js
  src/reducers/basketReducer.js
  src/reducers/customerReducer.js
  src/reducers/index.js
Labels: help wanted

#44 aligning routes, added thankyou to checkout
  src/components/Basket.js
  src/components/Checkout.js
Labels: help wanted

#45 Desktop two
  src/components/Basket.js
  src/components/Checkout.js
  src/reducers/basketReducer.js
  src/reducers/customerReducer.js
  src/reducers/index.js
Labels: enhancement

#48 need to add desktop image
  src/App.css
  src/components/Checkout.js
  src/components/Home.css
  src/components/Home.js
  src/components/Nav.js
Labels: enhancement

#49 New desktop
  src/App.css
  src/components/images/desktop.jpg
Labels: enhancement

#54 updatedproductname
  src/actions/productQuantity.js
  src/components/Checkout.js
  src/components/Home.js
  src/reducers/basketReducer.js
Labels: help wanted

#59 added checkIfNumber function
  src/components/Checkout.js
Labels: enhancement

#62 New create user
  src/components/Basket.js
  src/components/Checkout.js
  src/components/Signup.js
Labels: enhancement

#63 login form added
  src/components/Login.js
  src/components/Signup.js
Labels: enhancement
